events {
    worker_connections 1024;
}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;
    
    access_log /var/log/nginx/access.log;
    error_log /var/log/nginx/error.log;
    
    sendfile on;
    keepalive_timeout 65;
    
    upstream webapp {
        server webapp:5000;
    }
    
    upstream pgadmin_srv {
        server pgadmin:80;
    }
    
    server {
        listen 80;
        server_name localhost;
             
        location / {
            proxy_pass http://webapp;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
           
        location /pgadmin/ {
            proxy_pass http://pgadmin_srv/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Script-Name /pgadmin;
        }
    }
}